spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 331295045
    url: jdbc:mysql://localhost:3306/springboot1?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
　　filters: stat,wall,log4j     #druid监控配置
　　dbcp2:
　　min-idle: 5         #数据库连接池的最小维持连接数
　　initial-size: 5     #初始化提供的连接数
　　max-total: 5          #最大的连接数
　　max-wait-millis: 200        #等待连接获取的最大超时时间

server:
  port: 8081
